=== GhostWrench/CloVe/schemas/userdata.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "description": "Data that describes a person's professional experience",
    "type": "object",
    "required": [
        "personal_info",
        "skills",
        "projects"
    ],
    "properties": {
        "personal_info": {"$ref": "#/definitions/personal_info"},
        "skills": {
            "description": "A list of skills a person posseses",
            "type": "object",
            "additionalProperties": {"$ref": "#/definitions/skill"}
        },
        "projects": {
            "description": "Projects that a person has worked on",
            "type": "object",
            "additionalProperties": {"$ref": "#/definitions/project"}
        },
        "organizations": {
            "description": "Various organizations / companies that are relevant to the person",
            "type": "object",
            "additionalProperties": {"$ref": "#/definitions/organization"}
        }
    },
    "definitions": {
        "personal_info": {
            "description": "Basic information of the job seeker",
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "description": "Name of the person",
                    "type": "string"
                },
                "location": {
                    "description": "Location where the person lives",
                    "type": "string"
                },
                "website": {
                    "description": "Website address of the person's personal webpage",
                    "type": "string"
                }
            }
        },
        "skill": {
            "description": "Description and ability level for skill possessed by a person",
            "type": "object",
            "required": [
                "name",
                "ability"
            ],
            "properties": {
                "name": {
                    "description": "Short name of the skill",
                    "type": "string"
                },
                "ability": {
                    "description": "Ability level in the skill from 1 (beginner) to 10 (master)",
                    "type": "number",
                    "minimum": 1,
                    "maximum": 10
                },
                "description": {
                    "description": "Description of the skill (optional)",
                    "type": "string"
                }
            }
        },
        "project": {
            "description": "Description of a project that the applicant has worked on",
            "type": "object",
            "required": [
                "headline",
                "description",
                "prestige",
                "skills"
            ],
            "properties": {
                "headline": {
                    "description": "Short headline that identfies the project",
                    "type": "string"
                },
                "description": {
                    "decription": "Long description of the project and what the applicant's role",
                    "type": "string"
                },
                "prestige": {
                    "description": "Amount of prestige associated with the project from 1 (meh) to 10 (world changing)",
                    "type": "number",
                    "minimum": 1,
                    "maximum": 10
                },
                "skills": {
                    "description": "List of skill used in the course of the project",
                    "$comment": "This array must contain elements from #skills, but I don't know how to enforce via schema",
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    }
                },
                "organization": {
                    "description": "Name of the organiztion associated with the project",
                    "$comment": "This must match one of the organizations in the organization element, but I don't know if there is a way to enforce this constraint via a schema",
                    "type": "string"
                }
            }
        },
        "organization": {
            "description": "Organization or Employer that might be affiliated with a project or a person's employment history",
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "description": "Name of the organization",
                    "type": "string"
                },
                "description": {
                    "description": "Long description of the organization and/or the division worked for",
                    "type": "string"
                },
                "location": {
                    "description": "Location of the organization or where it was interacted with",
                    "type": "string"
                }
            }
        },
        "certification": {
            "description": "Certification obtained from a licencing body or university degree",
            "type": "object",
            "required": ["name", "organization"],
            "properties": {
                "name": {
                    "description": "Name of the certification",
                    "type": "string"
                },
                "organization": {
                    "description": "Name of the organiztion associated with the project",
                    "$comment": "This must match one of the organizations in the organization element, but I don't know if there is a way to enforce this constraint via a schema",
                    "type": "string"
                },
                "date" : {
                    "description": "Date that the certification was obtained",
                    "type": "string",
                    "format": "date"
                }
            }
        }
    }
}

=== GhostWrench/CloVe/example.userdata.json
{
    "$schema": "./schemas/userdata.json",
    "personal_info": {
        "name": "Daniel Kuntz",
        "location": "Arvada, Colorado",
        "website": "https://www.ghostwrench.net"
    },
    "skills": {
        "python": {
            "name": "Python",
            "ability": 10
        },
        "matlab": {
            "name": "MATLAB",
            "ability": 10
        },
        "simulink": {
            "name": "Simulink",
            "ability": 7
        },
        "c": {
            "name": "C",
            "description": "The C programming language",
            "ability": 8
        },
        "c++": {
            "name": "C++",
            "ability": 5
        },
        "javascript":
        {
            "name": "JavaScript",
            "ability": 7
        },
        "json": {
            "name": "JSON",
            "ability": 7
        },
        "html": {
            "name": "HTML 5",
            "ability": 4
        },
        "css": {
            "name": "CSS",
            "ability": 2
        },
        "java": {
            "name": "Java",
            "ability": 2
        },
        "dynamics": {
            "name": "Dynamic Systems Modeling",
            "ability": 9
        },
        "control": {
            "name": "Feedback Control Design",
            "description": "Design of feedback control algorithms for dynamic systems",
            "ability": 10
        },
        "estimation": {
            "name": "Dynamic Systems Estimation",
            "description": "Techniques for determining the state of an uncertain system with noisy measurements",
            "ability": 10
        },
        "writing": {
            "name": "Technical Writing",
            "ability": 9
        },
        "embedded": {
            "name": "Embedded Programming",
            "ability": 7
        },
        "web": {
            "name": "Web Design",
            "ability": 5
        },
        "android": {
            "name": "Android",
            "ability": 2
        },
        "linux": {
            "name": "Linux",
            "ability": 7
        },
        "windows": {
            "name": "Microsoft Windows",
            "ability": 7
        },
        "appsscript": {
            "name": "Google Apps Script",
            "ability": 6
        },
        "officejs": {
            "name": "Office.js",
            "ability": 1
        },
        "perforce": {
            "name": "Perforce",
            "description": "Perforce source control management software",
            "ability": 6
        },
        "git": {
            "name": "git",
            "description": "git Source control management software",
            "ability": 4
        },
        "excel": {
            "name": "Microsoft Excel",
            "ability": 9
        },
        "sheets": {
            "name": "Google Sheets",
            "ability": 9
        },
        "word": {
            "name": "Microsoft Word",
            "ability": 6
        },
        "docs": {
            "name": "Google Docs",
            "ability": 6
        },
        "solidworks": {
            "name": "SolidWorks",
            "description": "SolidWorks 3D Modeling Software",
            "ability": 4
        },
        "femap": {
            "name": "Femap",
            "description": "Femap FEA mesh generation software",
            "ability": 4
        },
        "nastran": {
            "name": "NX Nastran",
            "description": "NX Nastrain finite element analysis software",
            "ability": 4
        }
    },
    "projects": {
        "adaptive_observer": {
            "headline": "Load/Unload Adaptive Observer",
            "description": "Created an Kalman filter based observer to determine the location of an HDD actuator during load and unload operations when only noisy velocity measurements are available from the motor BEMF",
            "prestige": 9,
            "skills": ["dynamics", "estimation", "matlab", "c"],
            "organization": "seagate"
        },
        "servo_protocol": {
            "headline": "Servo Code API revisioning",
            "description": "Helped introduce a system for defining and revisioning the servo processor command interface along with documentation generation",
            "prestige": 7,
            "skills": ["python", "c", "json", "html", "css"],
            "organization": "seagate"
        }
    },
    "organizations": {
        "seagate": {
            "name": "Seagate Technology",
            "description": "Manufactuer of storage products, primarily Hard Disk Drives (HDDs)",
            "location": "Longmont, Colorado"
        }
    }

}
